name: Executar cada 5 minuts

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:      

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instal·lar dependències
      run: |
        pip install requests

    - name: Executar script
      run: |
        python temperatures.py
